# Basic band and deep imaging parameters.
band: L
scale: 1.1asec
weight: briggs -0.3
size: 10240
abs-threshold: 1e-6

# Extra input to the tron-pfb step.
transient-imaging.column.weight: WEIGHT_SPECTRUM
transient-imaging.htc.field-of-view: 2
transient-imaging.htc.super-resolution-factor: 1.1
transient-imaging.htc.robustness: -0.3
transient-imaging.htc.images-per-chunk: 16
transient-imaging.htc.max-simul-chunks: 5
transient-imaging.search-radius: 1
transient-imaging.breifast.reject-flux-threshold: "0.1"
transient-imaging.breifast.reject-mean-threshold: "0.1"
transient-imaging.primary-beam-band: "L"
transient-imaging.flag-cube.flag-excess-rms: 1.5
transient-imaging.breifast.candidate-threshold: 7
transient-imaging.breifast.detection-threshold: 8
transient-imaging.breifast.repeater-threshold: 7
transient-imaging.timescales: [0, FD, 15, 30, 60, 120, 240, 480, 960]
transient-imaging.enable-pimenton-cutouts: true
transient-imaging.include-all-regions: true
