# Basic band and deep imaging parameters.
band: L
scale: 1.1asec
weight: briggs -0.3
size: 10240
abs-threshold: 1e-6

# High time resolution imaging parameters.
htc_size: 3414
htc_scale: 3.3asec
htc_cadence: 1
htc_weight: briggs 0

