configuration:
  meerkat_uhf_band:
    wsclean_size: 8192
    wsclean_nchan: 8
    wsclean_auto_mask: 5
    wsclean_auto_thresh: 2
    weight: "briggs 0"
    pixel_scale: 2.4
    htc_size: 2048
    htc_scale: 9.6arcsec
    htc_cadence: 1
    htc_weight: "briggs 0"
    lightcurves-within: 1deg
    band: UHF
  meerkat_l_band:
    wsclean_size: 13000
    wsclean_nchan: 8
    wsclean_auto_mask: 5
    wsclean_auto_thresh: 2
    weight: "briggs 0"
    pixel_scale: 0.8
    htc_size: 3072
    htc_scale: 2.4arcsec
    htc_cadence: 1
    htc_weight: "briggs 0"
    lightcurves-within: 1deg
    band: L
  ata:
    wsclean_size: 2048
    wsclean_nchan: 8
    wsclean_auto_mask: 4
    wsclean_auto_thresh: 2
    weight: "briggs 0"
    pixel_scale: 3
    htc_size: 2048
    htc_scale: 3arcsec
    htc_cadence: 1
    htc_weight: "briggs 0"
    lightcurves-within: 1deg
    band: L  # Not currently configured.
